In [1]:
import numpy as np
import pandas as pd 
import os
import matplotlib.pyplot as plt
import joblib

plt.style.use("fivethirtyeight")

In [16]:
class Perceptron:
    def __init__(self, eta: float = None, epochs: int = None):
        self.weights = np.random.randn(3)*1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
    
    def fit(self, X, y): 
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        

In [17]:
obj = Perceptron(eta = 0.01, epochs = 10)

In [18]:
obj.eta

0.01

In [19]:
obj.epochs

10

In [20]:
obj.weights

array([-1.08063775e-04,  2.43169283e-04,  8.78667141e-05])

In [21]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
y = np.ones((4,1))

In [23]:
obj.fit(X, y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
